name: Integration Test Merlin API


runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - shell: bash
      run: |
        export TESTCONTAINERS_RYUK_DISABLED=true
        mvn integration-test -DskipUTs=true --settings settings.xml