name: Perform CDK Setup Operations
description: |
  Process the commands required for setting up AWS CDK
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Node Setup
      uses: actions/setup-node@v4
    - name: Setup Dependencies
      run: |
        npm install
        npm run build
      shell: bash