name: Package, Containerize, Release FDP

inputs:
  tag:
    required: true
    type: string
  package:
    required: true
    type: string


description: Package, Containerize, Release FDP
runs:
  using: composite
  steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.package }}

      - name: Configure AWS assume role
        uses: evinova/evinova-actions/actions/aws/assume_role@main # This apparently also sets up the CLI
        with:
          account_id: 719900980949
          region: eu-west-1
          role_name: MERLIN-DEV-DeploymentRole

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'



      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ inputs.tag }}
        shell:
        run: |
          tar xzvf ${{ inputs.package }} # Unzip Tar file to dist directory
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG